### ISSUE TITLE
Login fix for arise

### ISSUE THREAD

**Issue by TobiKaestle** [Viva-con-Agua/drops#272]
Old login with the pool and drops was with frontend redirection. We have to find a solution for arise now

**Comment by johannsell** [comment]
Can someone explain the issue to me, please? I don't get it. :)

Pool 1 redirects to Drops? I think it has to initiate the OAuth2-Handshake. Of course, this requires some redirects. This handshake tackles the front end if and only if, there is no logged in user. In that situation drops has to redirect to arise now, instead of Drops front end.

**Comment by deinelieblings** [comment]
drops logs: `[debug] - application - Failure on export!`

**Comment by deinelieblings** [comment]
When the path `/pool` is called, the pool1 tries to login the user via OAuth. So he redirects the browser to `Drops`, who either has a session or wants to log in the user. But `Drops` redirects to his own login page, not to `Arise` in the case the user has no session.
