### ISSUE TITLE
Split and Merge tasks

### ISSUE THREAD

**Issue by ottmann** [Viva-con-Agua/drops#52]
It should be possible to split and merge Tasks, when new Assignees will be selected. This is related to the Access Rights for this task.
This includes, that a supporter assigned to a task, and also when an supporter pass the task to one or more other supporters.

**Comment by johannsell** [comment]
If a task will be splitted, a subset of access rights should be assignable to each resulting new task.

**Comment by johannsell** [comment]
If a set of tasks will be merged, the set of sets of access rights will also be merged. Additionally a user should be able to define a new name and description. The names and descriptions of the original tasks should be visible the whole time. 

Three questions:
1.) What happens, if another supporter is associated to a subset of the merged set of tasks? 
--> Nothing happens, merged tasks will still remain the same set of splitted tasks for the other supporter.

2.) What happens, if another supporter is associated to the same set of tasks, that arfe merged?
--> User can choose between merge only for him-/herself or escalate it to all other supporter

3.) What happens, if the (sub-)set of tasks is associated to a role that is associated to the user?
--> It's not possible to merge these tasks.


--> Split & Merge is to complicated! Rejected, since split & merge could be done using Create & Delete
